### PR TITLE
Update bungeecord-api dependancy

### PR DESCRIPTION
**Pull request by Konicai**
bungeecord-api has been updated from `1.16-R0.4-SNAPSHOT` to `1.16-R0.5-SNAPSHOT`.

### CODE REVIEW

**Comment by Camotoy** [comment]
Thanks for the PR! The reason I haven't merged this is because the R0.4 version is still supported by Geyser since it accepts 1.16.4.

**Comment by Konicai** [comment]
fixed :)

**Comment by Camotoy** [comment]
Does it compile?

**Comment by Konicai** [comment]
Sorry, I wasn't clear

It does compile, as the jar files for `1.16-R0.4` are available. They no longer are in `1.16-R0.4-SNAPSHOT`, which now only contains some hashes. 

https://oss.sonatype.org/content/groups/public/net/md-5/bungeecord-api/

**Comment by Camotoy** [comment]
OK. Thanks!

**Pull request merged**
